### ISSUE TITLE
Rebuild pip mirror for production

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-debian-packaging#110]
related to #109

prior to the production release of the workstation, we should rebuild our pip mirror for production. If you're wondering "let's just have a separate prod pip mirror" - one problem with this is that we point to the hashes of the built wheels in build-requirements.txt in each project, which means that as I see it we would need to:
1. have multiple build-requirements.txt files, one for CI builds, one for prod, OR
2. include the hashes of both "dev" wheels and prod wheels in the build requirements file 

Both 1 and 2 are pretty annoying I think, 2 in particular seems like a recipe for disaster in the future (mixing prod requirements with test/dev requirements). 

So instead: we just use one pip mirror, and ensure that everything that is committed to it is production-ready. 

A builder will build the wheels, use the signing ceremony to sign the sha256sums.txt associated with those wheel builds, and commit them. At this point all build-requirements.txt will need to be updated to point to the new wheels.

**Comment by redshiftzero** [comment]
When we perform this rebuild, we'll sign the shasums file with the official release key and remove the other authorized keys.

**Comment by conorsch** [comment]
#109 is now complete, so removing the "blocked" label here.
