### ISSUE TITLE
Consider submodules to track all workstation repositories to aid in release builds and verification

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-debian-packaging#113]
For every workstation release, we will need to capture the version/commit/tag of every single repository used for the Workstation, for change control purposes:
- securedrop-workstation
- securedrop-client
- securedrop-proxy
- securedrop-sdk
- securedrop-export
- securedrop-log
- ansible-role-grsecurity-build
- securedrop-workstation-svs-disp
- securedrop-workstation-grsec
- securedrop-workstation-config

To ensure integrity of this code, these tags should be signed and tracked, for each one of the repositories above, to ensure the correct commits across each repository are used.

One way we could simplify this process is to use this repository as the "main" repository, and pull in all the repositories above as submodules. When creating a release, we create a signed tag that pins hashes of commits used for the release across all Workstation repositories. 

When building the debs for a specific release, a single securedrop-debian-packaging release-key-signed tag will be checked out and pull in submodule hashes for every single securedrop-* package, verify the last commit or tag in each of those repos (to ensure they were signed by a trusted developer), and then the packages can be built. This will allow us to also be able to build historical packages, as long as the pip wheels are still on the PyPi mirror.

If we decide to use this approach, we could consider a new repository, but this repository sounds like the logical place to do so.

**Comment by redshiftzero** [comment]
marking this as blocked for now until we resolve the signing story for the workstation

**Comment by redshiftzero** [comment]
closing this one as after discussion, the signing story will not require submodules. Instead, we will sign the tag in each subcomponent with the official release key and verify that tag prior to build. We will also need to sign the build logic itself prior to running it, that can be done independently of this.
