### ISSUE TITLE
add CI job to verify tarballs are signed with release key

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-debian-packaging#147]
In https://github.com/freedomofpress/securedrop-debian-packaging/pull/146 we are adding source tarballs with detached sigs for prod-ready releases of the workstation. We could add a CI job to prevent accidental merge of artifacts that are not signed with the SD release key.

**Comment by eloquence** [comment]
As discussed in #195, we may end up removing `tarballs` from this repo, at which point this check would become unnecessary. Keeping open for now until we've made a final decision on that point as this check would certainly be useful until then.

**Comment by eloquence** [comment]
We have discontinued the use of the tarballs directory in the latest release, and are likely to phase it out completely, so closing this issue.
