### ISSUE TITLE
remove wheelsurls.txt

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-debian-packaging#166]
do we need to maintain `wheelsurls.txt` anymore? If I recall correctly, we had this back when we were storing wheels on S3, and we used `wheelsurls.txt` as a convenient way to sync all the existing wheels on S3 back to the user's local machine. Since we're now using `git lfs` and as such have the wheels locally with a git checkout, I think we can get rid of `wheelsurls.txt` and any related scripts/makefile targets. 

If I'm wrong and it _is_ needed we should document where/why.

**Comment by redshiftzero** [comment]
this is a question for probably @kushaldas :-)

**Comment by kushaldas** [comment]
I agree and we should remove it.
