### ISSUE TITLE
Error when i try to build deb package on buster machine

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-debian-packaging#181]
# Description

Currently I build debs on a qubes buster vm using the debian-10 template that I set up a while back. I'm able to build debs easily by running `make install-deps` followed by `PKG_PATH=<tarball> PKG_VERSION=<version> make <project>` but when I follow the same steps on my buster machine, I see the following error during the `make <project>` command:

```
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 110, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 87, in main
    deploy.create_virtualenv()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 157, in create_virtualenv
    subprocess.check_call(virtualenv)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--system-site-packages', '--setuptools', '--python', '/usr/bin/python3', 'debian/securedrop-client/opt/venvs/securedrop-client']' returned non-zero exit status 2
make[2]: *** [debian/rules:7: override_dh_virtualenv] Error 1
make[2]: Leaving directory '/home/creviera/debbuild/packaging/securedrop-client'
make[1]: *** [debian/rules:4: binary] Error 2
make[1]: Leaving directory '/home/creviera/debbuild/packaging/securedrop-client'
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
make: *** [Makefile:9: securedrop-client] Error 2
```

Here's one of my attempts to make a deb using our packaging scripts that includes the error above:
[build-logs.txt](https://github.com/freedomofpress/securedrop-debian-packaging/files/4950351/build-logs.txt)

I verified that the dependencies are all installed, but perhaps there is a missing dependency in the [install-deps](https://github.com/freedomofpress/securedrop-debian-packaging/blob/main/scripts/install-deps) script?

Opening in case this is a bug and to help me track this issue. Right now, I prefer to use my Qubes workstation for building packages in a VM, but it would be great if this could work on my development laptop in case I don't have my Qubes machine.

**Comment by legoktm** [comment]
Looking at the build-logs, this seems to be the same issue as #260. In any case, we no longer support buster plus I'm pretty sure @creviera has successfully built packages since this was filed :)
