### ISSUE TITLE
Further automate html generation with updateindex.py

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-debian-packaging#200]
https://github.com/freedomofpress/securedrop-debian-packaging/blob/main/scripts/updateindex.py will only update the index for the root of the website, and not within the wheel subfolder: those need to be updated manually by a developer.

We should update this script in order to generate this HTML automatically, removing the need for a developer to manually edit html files for the pypi mirror.

**Comment by legoktm** [comment]
The `simple/` HTML index files were removed in 0e14f0ce4fb1b2175a60ed56926cd336cc4dc09a, so I'm closing this as obsolete, and will submit a PR to remove the `updateindex.py` script.
