### ISSUE TITLE
No new nightlies since January 25

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-debian-packaging#216]
No new SecureDrop Workstation nightlies have been commited to https://github.com/freedomofpress/securedrop-dev-packages-lfs by `sdcibot` since January 25.

**Comment by eloquence** [comment]
Example job failure output: https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/896/workflows/44399b08-d0ed-4445-b1f9-37cf7e0bdad7/jobs/6889

**Comment by conorsch** [comment]
Rats, the nightly logic didn't run on PR for https://github.com/freedomofpress/securedrop-debian-packaging/pull/213, so I missed the breakage on the nightly paths. Will take a look at this tomorrow to unbreak!
