### ISSUE TITLE
Update securedrop-keyring package for TemplateVMs

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-debian-packaging#249]
Towards https://github.com/freedomofpress/securedrop/issues/5923. In order to rotate the SecureDrop Release Signing Key on the workstation, we must bump the public keyring in the `securedrop-keyring` package, used in the Debian-based VMs. The package config is here: https://github.com/freedomofpress/securedrop-debian-packaging/tree/963db4100e0dfb5d5ccc019e8b70afe4441f6cab/securedrop-keyring

Note that there's a separate `securedrop-keyring` package for the servers, changes for which are visible in https://github.com/freedomofpress/securedrop/pull/5930. The same changes should be replicated in the workstation package: version bump, and import new pubkey into the existing keyring, so two pubkeys are present.

**Comment by eloquence** [comment]
(Transferred into this repo since the package config lives here.)

**Comment by eloquence** [comment]
The package was updated via https://github.com/freedomofpress/securedrop-debian-packaging/pull/250; keeping open until release (can of course also be split into a follow-up issue).

**Comment by conorsch** [comment]
As mentioned in https://github.com/freedomofpress/qubes-template-securedrop-workstation/issues/20#issuecomment-853344393, the 0.1.5 keyring packaged has been released to prod, so closing.
