### ISSUE TITLE
virtualenv: error: argument --setuptools: expected one argument

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-debian-packaging#260]
I think `virtualenv` has upgraded and now expects a version to follow the argument: `--setuptools`, so we need to update our packaging logic to avoid the following error:

```
virtualenv: error: argument --setuptools: expected one argument
SystemExit: 2
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 110, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 87, in main
    deploy.create_virtualenv()
  File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 157, in create_virtualenv
    subprocess.check_call(virtualenv)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--system-site-packages', '--setuptools', '--python', '/usr/bin/python3', 'debian/securedrop-client/opt/venvs/securedrop-client']' returned non-zero exit status 2
make[2]: *** [debian/rules:7: override_dh_virtualenv] Error 1
make[2]: Leaving directory '/home/creviera/workspace/freedomofpress/securedrop-debian-packaging/build/debbuild/packaging/securedrop-client'
make[1]: *** [debian/rules:4: binary] Error 2
make[1]: Leaving directory '/home/creviera/workspace/freedomofpress/securedrop-debian-packaging/build/debbuild/packaging/securedrop-client'
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
make: *** [Makefile:9: securedrop-client] Error 2
```

## STR
1. update client changelog for an rc: `./update-changelog.sh 0.5.0~rc1`
2. build client rc tarball: `python3 setup.py sdist`
3. switch over to this repo
4. update debian packaging changelog for the client rc: `PKG_VERSION=0.5.0~rc1 ./scripts/update-changelog securedrop-client`
5. run `PKG_VERSION=0.5.0-rc1 PKG_PATH=/home/creviera/workspace/freedomofpress/securedrop-client/dist/securedrop-client-0.5.0-rc1.tar.gz make securedrop-client`

## Expected
for an rc deb to be built 

## Actual
the error above

**Comment by conorsch** [comment]
The `/usr/lib/python2.7/` path in the error output shows python2 is being used. Make sure to activate your python3-based virtualenv locally, then try again!

**Comment by kushaldas** [comment]
> The `/usr/lib/python2.7/` path in the error output shows python2 is being used. Make sure to activate your python3-based virtualenv locally, then try again!

Python2 is the correct path here, because on Debioan Buster, the `dh-virtualenv` tool is packaged against Python2. We can fix the issue in simple way by using `--builtin-venv` flag in the rules file, and `--upgrade-pip` flags. These will use the system `venv` module to create the virtualenv and then will update `pip` itself so that our build flags actually work.  

This originally happened because we now have a new version of `virtualenv` package in Debian Buster than what we had before.  We now just have to figure out how to have `~rcX` in the version string of the `changelog` files.

**Comment by creviera** [comment]
note (specifically to @eloquence when you get to QA'ing next week): i ran out of time today, but i had to apply this patch, supplied by kushal to get an rc package to build and get past this error:

```
diff --git a/securedrop-client/debian/changelog-buster b/securedrop-client/debian/changelog-buster
index 76e8749..d28cad4 100644
--- a/securedrop-client/debian/changelog-buster
+++ b/securedrop-client/debian/changelog-buster
@@ -1,3 +1,9 @@
+securedrop-client (0.5.0rc1+buster) unstable; urgency=medium
+
+  * 
+
+ -- SecureDrop Team <securedrop@freedom.press>  Thu, 12 Aug 2021 09:40:39 -0700
+
 securedrop-client (0.4.1+buster) unstable; urgency=medium
 
   * See changelog.md 
diff --git a/securedrop-client/debian/rules b/securedrop-client/debian/rules
index 6111b4c..35b2823 100755
--- a/securedrop-client/debian/rules
+++ b/securedrop-client/debian/rules
@@ -7,6 +7,8 @@ override_dh_virtualenv:
 	dh_virtualenv \
 		--python /usr/bin/python3 \
 		--setuptools \
+		--builtin-venv \
+		--upgrade-pip \
 		--use-system-packages \
 		--extra-pip-arg "--ignore-installed" \
 		--extra-pip-arg "--no-index" \
```

**Comment by creviera** [comment]
note: i had to modify the rc build process like so (using `0.5.0rc1` instead of `0.5.0~rc1`):

1. update client changelog for an rc: `./update-changelog.sh 0.5.0rc1`
2. build client rc tarball: `python3 setup.py sdist`
3. switch over to this repo
4. update debian packaging changelog for the client rc: `PKG_VERSION=0.5.0rc1 ./scripts/update-changelog securedrop-client`
5. run `PKG_VERSION=0.5.0rc1 PKG_PATH=/home/creviera/workspace/freedomofpress/securedrop-client/dist/securedrop-client-0.5.0rc1.tar.gz make securedrop-client`

**Comment by eloquence** [comment]
(I did not follow the exact same STR, but I did not encounter this issue when building a 0.5.0 deb in a Buster-based VM.)

**Comment by kushaldas** [comment]
After digging more in Debian Buster I can confirm that the version of [virtualenv](https://packages.debian.org/buster/virtualenv) is `15.1.0+ds-2`. But, the version running on @creviera's system is `20.4.3` which is installed in `/usr/local/bin`. This means somehow the package was installed on that system from upsteam release. Maybe there was a `sudo pip install virtualenv` done for some reason.

I will investigate more along with @creviera when she is online.

**Comment by creviera** [comment]
ah, if this is an allie-only issue, perhaps we should close this? @kushaldas curious what you think and if it would hurt to add the `--upgrade-pip` and `--builtin-venv` flags since they do fix the issue for me.

**Comment by legoktm** [comment]
We removed `--setuptools` from all the `d/rules` files during the migration to bullseye for precisely this reason.
