### ISSUE TITLE
Add babel and pip-tools to build requirements

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-debian-packaging#274]
# Description

In order to add translation support to our packaging tool, we'll need to diff-review a couple dependencies (pip-tools and babel) and their dependencies (click and pytz), see https://github.com/freedomofpress/securedrop-debian-packaging/pull/270/files#diff-6bb1a5aa941fac1c395883fe3d8d441b345c8267e959decaa615e74e89de0542

This issue is to track that work. For a step-by-step guide on how to do a diff review and for more information on _why_ we go through the trouble, see https://github.com/freedomofpress/securedrop-debian-packaging/wiki/FAQ

1. [x] [`babel` 2.9.1](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/Babel-2.5.1-to-2.9.1)
    1. [x] [`pytz` 2021.1](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/pytz-2021.1)
 2. [x] [`pip-tools` 6.0.1](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/pip-tools-6.0.1)
     1. [x] [`click` 7.1.2](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/click-7.1.2)

**Comment by cfm** [comment]
@creviera, is it relevant that a diff review is [already confirmed for the Babel 2.9.1 dependency](https://github.com/freedomofpress/securedrop-debian-packaging/wiki/Babel-2.5.1-to-2.9.1) originating from `securedrop`?  (If indeed this unblocks #270, I'm sorry I didn't make this connection more explicit there or catch this sooner last week!)

**Comment by creviera** [comment]
absolutely did you find the rest of the dependency diff reviews?

**Comment by cfm** [comment]
Per out-of-band discussion with @creviera today, I will perform an initial diff review tomorrow for her review and maintainer's sign-off.

**Comment by creviera** [comment]
> @creviera, I've conducted the initial reviews linked above per the instructions for adding new dependencies. The only noteworthy findings are 7 high-severity Bandit alerts for Click, but these arise in platform-specific implementations of interactive terminal features that I believe we can accept in context. Feedback and next steps welcome!

I reviewed the diffs and I think we can accept your sign-off here, but would like to verify this with @conorsch first before unblocking  https://github.com/freedomofpress/securedrop-debian-packaging/pull/270

**Comment by kushaldas** [comment]
> I reviewed the diffs and I think we can accept your work here, but would like to verify this with another maintainer -- @kushaldas, how do these diffs look? If they look good to you too, perhaps we could get your signature as needed to unblock #270?

The reviews look okay. I will go ahead and review #270 now.

**Comment by kushaldas** [comment]
This is good now, I am closing this.
