### ISSUE TITLE
Publish workstation nightlies or rcs to a separate component on apt-test

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-debian-packaging#289]
Currently the workstation nightly package building had to be paused while manually built rcs were pushed to apt-test.

We could push the nightlies or rcs to a separate component on apt-test so the two don't conflict and people can use whichever they want to test. Adding a new component should be as simple as adding a new name to https://github.com/freedomofpress/securedrop-dev-packages-lfs/blob/main/repo/conf/distributions#L11 and setting up a new folder to push in.

If we decide to put nightlies in a "nightlies" component, in sources.list it would look like:
```
deb https://apt-test.freedom.press/ buster nightlies
```

**Comment by legoktm** [comment]
In one of the meetings this or last week (I forgot), this was specifically brought up as some low hanging fruit and there were no objections at the time so I intend to (slowly) move forward on this.

We first need to teach our reprepro script about components, currently it assumes everything goes into the "main" component.

Our directory layout looks like `core/focal`, `workstation/buster`, where the first name is just a folder to look into, and the second is the codename. The simplest way is to have the second name also include the component, like `workstation/buster-nightlies`. If there's no dash in the name, it'll default back to "main" (status quo).

Note that we'll actually need to finish cleaning up the `template-consolidation` folder that hasn't been used since Oct. 2020.

Then we update CI to push nightlies to the new folder and instruct everyone who's using them to update their sources.list. It'll take a manual rebuild on `apt-test` to cleanup the existing debs.

**Comment by eloquence** [comment]
It'd be nice to have convenience `Makefile` targets in `securedrop-workstation` to switch between components, I think. I suspect we'll still want to default to the nightlies for `staging` and `dev` environments and offer a simple way to switch to the `release-candidates` component with either of those environments active (or back to `nightly`).

**Comment by legoktm** [comment]
That seems doable...there's already a [qa-switch](https://github.com/freedomofpress/securedrop-workstation/blob/main/utils/qa-switch.sh) tool for switch from prod to apt-test, we'd just need to introduce a third-state of nightly.

**Comment by legoktm** [comment]
Summary of the PRs:
* https://github.com/freedomofpress/securedrop-workstation/pull/762 - enhances the developer experience, I haven't tested it yet, should get to that next week.
* https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/145 - teaches reprepro about the new component, moves existing packages over
* https://github.com/freedomofpress/securedrop-debian-packaging/pull/302 - tells CI to copy packages over into the new directory/component

**Comment by creviera** [comment]
> It'd be nice to have convenience `Makefile` targets in `securedrop-workstation` to switch between components, I think. I suspect we'll still want to default to the nightlies for `staging` and `dev` environments and offer a simple way to switch to the `release-candidates` component with either of those environments active (or back to `nightly`).

Yes, a way to use a Makefile target to switch between nightlies and release-candidates would be helpful.
