### ISSUE TITLE
Build bullseye packages

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-debian-packaging#321]
We need bullseye packages for the upcoming buster EOL. An initial builder was added in #317.

For each package:
* [ ] Configure CI to run tests on bullseye/Python 3.9 (in component repo)
* [ ] Build the package under bullseye:
  * [ ] Remove `--setuptools`, no-op in buster and bullseye
  * [ ] Rebuild localwheels for Python 3.9
  * [ ] Upgrade to debian-compat = 12 (see https://nthykier.wordpress.com/2019/01/04/debhelper-compat-12-is-now-released/)
* [ ] Configure CI to build bullseye nightlies (in packaging repo)
* [ ] Configure CI to build bullseye packages (in component repo)

**Comment by legoktm** [comment]
With #322, I tested building a few packages and it seems we're ready to work on individual packages now. The plan is for me to pair with different people who expressed interest, and each pair can tackle 1-2 packages. I think our success criteria will be that the package was built successfully and looks reasonable (like, it contains the necessary files). Testing is going to be hard since we can't use debdiff/diffoscope since all the files moved from python3.7 -> python3.9, and we really need *all* the packages to effectively test SDW. So that'll have to be a collective step once we're done.

**Comment by creviera** [comment]
Super helpful checklist @legoktm, thanks! Tomorrow, it would make sense to start with the `securedrop-keyring` package (https://github.com/freedomofpress/securedrop-debian-packaging/issues/319) if you don't mind pairing with someone on that (I volunteer for this first one if no one else does).

**Comment by creviera** [comment]
At this point, we have all the nightlies building for bullseye, so closing this tracking issue. Please reopen if I missed anything.
