### ISSUE TITLE
`securedrop-export` has uninstallable dependencies

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-debian-packaging#343]
`securedrop-export_0.2.6-dev-20220616-061827+bullseye_all.deb` is uninstallable because of unmet dependencies from:

https://github.com/freedomofpress/securedrop-debian-packaging/blob/b5cc86535fd3f678edce03fa0214e25d085f7632/securedrop-export/debian/control#L13

```sh-session
user@sd-large-bullseye-template:~$ sudo apt install securedrop-export
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 securedrop-export : Depends: task-print-server but it is not installable
                     Depends: xpp but it is not installable
E: Unable to correct problems, you have held broken packages.
```

- [x] `task-print-server`: remove
    - #344 
- [x] `xpp`: test and host ourselves for bullseye, like freedomofpress/securedrop-dev-packages-lfs#155
    - freedomofpress/securedrop-dev-packages-lfs#161

Blocks freedomofpress/securedrop-workstation#784.

**Comment by cfm** [comment]
After initial research, my understanding is that, while both `task-print-server` and `xpp` have been removed from Debian stable as of bullseye:

1. **`task-print-server` we can remove entirely,** since we have explicit `Depends` for both `cups` and `system-config-printer`, which should be able to take advantage of bullseye's ["driverless" printing](https://wiki.debian.org/CUPSDriverlessPrinting) via `ipp-usb`; whereas
2. **`xpp` we'll have to test and host ourselves,** [as we now do for `paxctld`](https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/155), because it's [explicitly invoked by `securedrop-client`](https://github.com/freedomofpress/securedrop-export/blob/281d1f9b2183841102dc16e6036f9d900d31c942/securedrop_export/print/actions.py#L217).

I'll prepare a pull request based on this interpretation, but I'd appreciate confirmation from @creviera and @legoktm about (respectively) the Client- and bullseye-specific points here.

**Comment by creviera** [comment]
@cfm your plan looks good to me!
