### ISSUE TITLE
`securedrop-workstation-config`: Update mimeapps.list files for bullseye

### ISSUE THREAD

**Issue by eaon** [freedomofpress/securedrop-debian-packaging#348]
`securedrop-workstation` tests for the sd-viewer DispVM template are failing at the moment on 4.1. On bullseye `eog.desktop` does not exist and neither `xdg-open example.jpg` nor `xdg-mime query default image/jpeg` work as expected because the desktop file for Eye of GNOME has been renamed to `org.gnome.eog.desktop`.

Hence: mentions of `eog.desktop` ought to be updated for bullseye.

**Comment by eloquence** [comment]
For other file types, we used [this spreadsheet](https://docs.google.com/spreadsheets/d/1l-DGR5UnnvYA5jfeZtplER933ANPWgFLx_uWbnJZKWI/edit#gid=0) back in 2019 to document expected/desired behavior, which may still serve as a useful reference point during QA. (In addition, MP4 audio support was added later.)
