### ISSUE TITLE
Document process around building and testing new containers before pushing them to quay.io

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-debian-packaging#363]
## Description

For the workstation, we maintain images of our build containers in quay.io for a CI job that runs a reproducible wheels test, but it's not clear why we do this or when to update those containers or how to test. I think some documentation in our wiki or readme would be helpful.

See https://github.com/freedomofpress/securedrop-debian-packaging/pull/317 and #350 for an idea on how this can get confusing.

**Comment by eloquence** [comment]
Looks like the original motivation was reproducibility breakage with the CircleCI-provided images (#253) which was addressed via #254.

**Comment by legoktm** [comment]
I removed the custom dockerfiles in 3c81ff81617ba3729ea1006bcf1143c07d446235, we now use plain Debian images for everything, and no longer need to push/maintain anything on quay.io!
