### ISSUE TITLE
Modify nightly build logic to include version bumps

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-debian-packaging#50]
- Part of build automation epic (#8)
- Pending merge of #44
- Pending completion of version bump scripts: https://github.com/freedomofpress/securedrop-client/issues/407 and https://github.com/freedomofpress/securedrop-proxy/issues/34

We'll want to modify the nightly build logic to include these version bumps, so that we can commit uniquely identified nightly builds to our LFS repository.

**Comment by redshiftzero** [comment]
The securedrop-client side of this is done, the securedrop-proxy side of this is currently blocked on merge of https://github.com/freedomofpress/securedrop-proxy/pull/37
