### ISSUE TITLE
Update package build logic to support securedrop-proxy builds on Buster

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-debian-packaging#91]
Part of epic: https://github.com/freedomofpress/securedrop-workstation/issues/306

#89 adds support for securedrop-client builds on Debian Buster. We need to do the same for securedrop-proxy.

**Comment by redshiftzero** [comment]
first we need to do a securedrop-proxy release - @creviera want to do that today and i can review? 

For background for the interested observer, the reason why we need a `securedrop-proxy` release before adding buster builds is that the `build-requirements.txt` in that repository needs to point to the wheels on both 3.5 (stretch) and 3.7 (buster). Fortunately @kushaldas made that change already in https://github.com/freedomofpress/securedrop-proxy/pull/49 so we just need to make a new release including his change ✨

**Comment by redshiftzero** [comment]
done in #97

(made a card on the board for the package release)
